[2021-10-18 18:15:36,454] {processor.py:163} INFO - Started process (PID=1856) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:15:36,455] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:15:36,456] {logging_mixin.py:109} INFO - [2021-10-18 18:15:36,456] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:15:36,561] {logging_mixin.py:109} INFO - [2021-10-18 18:15:36,559] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:15:36,575] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:15:36,582] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.132 seconds
[2021-10-18 18:16:06,643] {processor.py:163} INFO - Started process (PID=1886) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:16:06,645] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:16:06,646] {logging_mixin.py:109} INFO - [2021-10-18 18:16:06,646] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:16:06,748] {logging_mixin.py:109} INFO - [2021-10-18 18:16:06,746] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:16:06,762] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:16:06,768] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.128 seconds
[2021-10-18 18:16:35,729] {processor.py:163} INFO - Started process (PID=1909) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:16:35,731] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:16:35,732] {logging_mixin.py:109} INFO - [2021-10-18 18:16:35,732] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:16:35,848] {logging_mixin.py:109} INFO - [2021-10-18 18:16:35,846] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:16:35,865] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:16:35,872] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.146 seconds
[2021-10-18 18:17:05,941] {processor.py:163} INFO - Started process (PID=1931) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:17:05,943] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:17:05,944] {logging_mixin.py:109} INFO - [2021-10-18 18:17:05,944] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:17:06,054] {logging_mixin.py:109} INFO - [2021-10-18 18:17:06,053] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:17:06,068] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:17:06,074] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.138 seconds
[2021-10-18 18:17:36,148] {processor.py:163} INFO - Started process (PID=1962) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:17:36,151] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:17:36,152] {logging_mixin.py:109} INFO - [2021-10-18 18:17:36,152] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:17:36,254] {logging_mixin.py:109} INFO - [2021-10-18 18:17:36,252] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:17:36,268] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:17:36,274] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.130 seconds
[2021-10-18 18:18:06,340] {processor.py:163} INFO - Started process (PID=1990) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:18:06,343] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:18:06,344] {logging_mixin.py:109} INFO - [2021-10-18 18:18:06,344] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:18:06,452] {logging_mixin.py:109} INFO - [2021-10-18 18:18:06,451] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:18:06,468] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:18:06,474] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.138 seconds
[2021-10-18 18:18:36,560] {processor.py:163} INFO - Started process (PID=2014) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:18:36,562] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:18:36,563] {logging_mixin.py:109} INFO - [2021-10-18 18:18:36,563] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:18:36,673] {logging_mixin.py:109} INFO - [2021-10-18 18:18:36,672] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:18:36,686] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:18:36,692] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.136 seconds
[2021-10-18 18:19:06,755] {processor.py:163} INFO - Started process (PID=2045) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:19:06,757] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:19:06,759] {logging_mixin.py:109} INFO - [2021-10-18 18:19:06,759] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:19:06,867] {logging_mixin.py:109} INFO - [2021-10-18 18:19:06,866] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:19:06,881] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:19:06,887] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.135 seconds
[2021-10-18 18:19:36,956] {processor.py:163} INFO - Started process (PID=2067) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:19:36,958] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:19:36,960] {logging_mixin.py:109} INFO - [2021-10-18 18:19:36,960] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:19:37,072] {logging_mixin.py:109} INFO - [2021-10-18 18:19:37,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:19:37,087] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:19:37,094] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.142 seconds
[2021-10-18 18:20:07,166] {processor.py:163} INFO - Started process (PID=2098) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:20:07,168] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:20:07,169] {logging_mixin.py:109} INFO - [2021-10-18 18:20:07,169] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:20:07,272] {logging_mixin.py:109} INFO - [2021-10-18 18:20:07,271] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:20:07,288] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:20:07,294] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.132 seconds
[2021-10-18 18:20:37,372] {processor.py:163} INFO - Started process (PID=2120) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:20:37,374] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:20:37,376] {logging_mixin.py:109} INFO - [2021-10-18 18:20:37,375] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:20:37,485] {logging_mixin.py:109} INFO - [2021-10-18 18:20:37,484] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:20:37,499] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:20:37,504] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.136 seconds
[2021-10-18 18:21:07,554] {processor.py:163} INFO - Started process (PID=2152) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:21:07,556] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:21:07,557] {logging_mixin.py:109} INFO - [2021-10-18 18:21:07,557] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:21:07,660] {logging_mixin.py:109} INFO - [2021-10-18 18:21:07,659] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:21:07,674] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:21:07,680] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.130 seconds
[2021-10-18 18:21:37,760] {processor.py:163} INFO - Started process (PID=2173) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:21:37,762] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:21:37,763] {logging_mixin.py:109} INFO - [2021-10-18 18:21:37,763] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:21:37,871] {logging_mixin.py:109} INFO - [2021-10-18 18:21:37,870] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:21:37,887] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:21:37,894] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.138 seconds
[2021-10-18 18:22:07,944] {processor.py:163} INFO - Started process (PID=2204) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:22:07,946] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:22:07,947] {logging_mixin.py:109} INFO - [2021-10-18 18:22:07,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:22:08,048] {logging_mixin.py:109} INFO - [2021-10-18 18:22:08,046] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:22:08,061] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:22:08,067] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.127 seconds
[2021-10-18 18:22:38,133] {processor.py:163} INFO - Started process (PID=2225) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:22:38,135] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:22:38,136] {logging_mixin.py:109} INFO - [2021-10-18 18:22:38,136] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:22:38,242] {logging_mixin.py:109} INFO - [2021-10-18 18:22:38,240] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:22:38,256] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:22:38,261] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.133 seconds
[2021-10-18 18:23:08,328] {processor.py:163} INFO - Started process (PID=2256) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:23:08,330] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:23:08,331] {logging_mixin.py:109} INFO - [2021-10-18 18:23:08,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:23:08,438] {logging_mixin.py:109} INFO - [2021-10-18 18:23:08,436] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:23:08,451] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:23:08,457] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.133 seconds
[2021-10-18 18:23:38,507] {processor.py:163} INFO - Started process (PID=2277) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:23:38,509] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:23:38,511] {logging_mixin.py:109} INFO - [2021-10-18 18:23:38,510] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:23:38,608] {logging_mixin.py:109} INFO - [2021-10-18 18:23:38,607] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:23:38,623] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:23:38,629] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.125 seconds
[2021-10-18 18:24:08,674] {processor.py:163} INFO - Started process (PID=2309) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:24:08,675] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:24:08,677] {logging_mixin.py:109} INFO - [2021-10-18 18:24:08,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:24:08,776] {logging_mixin.py:109} INFO - [2021-10-18 18:24:08,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:24:08,790] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:24:08,797] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.127 seconds
[2021-10-18 18:24:38,875] {processor.py:163} INFO - Started process (PID=2330) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:24:38,876] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:24:38,878] {logging_mixin.py:109} INFO - [2021-10-18 18:24:38,877] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:24:38,978] {logging_mixin.py:109} INFO - [2021-10-18 18:24:38,975] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:24:38,991] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:24:38,997] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.126 seconds
[2021-10-18 18:25:09,053] {processor.py:163} INFO - Started process (PID=2362) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:25:09,055] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:25:09,056] {logging_mixin.py:109} INFO - [2021-10-18 18:25:09,056] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:25:09,157] {logging_mixin.py:109} INFO - [2021-10-18 18:25:09,155] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:25:09,171] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:25:09,177] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.127 seconds
[2021-10-18 18:25:39,251] {processor.py:163} INFO - Started process (PID=2383) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:25:39,253] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:25:39,254] {logging_mixin.py:109} INFO - [2021-10-18 18:25:39,254] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:25:39,359] {logging_mixin.py:109} INFO - [2021-10-18 18:25:39,358] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:25:39,373] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:25:39,379] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.131 seconds
[2021-10-18 18:26:09,447] {processor.py:163} INFO - Started process (PID=2415) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:26:09,450] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:26:09,451] {logging_mixin.py:109} INFO - [2021-10-18 18:26:09,451] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:26:09,554] {logging_mixin.py:109} INFO - [2021-10-18 18:26:09,553] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:26:09,568] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:26:09,573] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.131 seconds
[2021-10-18 18:26:39,649] {processor.py:163} INFO - Started process (PID=2437) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:26:39,651] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:26:39,652] {logging_mixin.py:109} INFO - [2021-10-18 18:26:39,652] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:26:39,753] {logging_mixin.py:109} INFO - [2021-10-18 18:26:39,752] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:26:39,767] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:26:39,772] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.128 seconds
[2021-10-18 18:27:09,845] {processor.py:163} INFO - Started process (PID=2468) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:27:09,847] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:27:09,848] {logging_mixin.py:109} INFO - [2021-10-18 18:27:09,848] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:27:09,947] {logging_mixin.py:109} INFO - [2021-10-18 18:27:09,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:27:09,960] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:27:09,965] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.125 seconds
[2021-10-18 18:27:40,045] {processor.py:163} INFO - Started process (PID=2489) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:27:40,047] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:27:40,048] {logging_mixin.py:109} INFO - [2021-10-18 18:27:40,048] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:27:40,156] {logging_mixin.py:109} INFO - [2021-10-18 18:27:40,155] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:27:40,179] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:27:40,184] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.144 seconds
[2021-10-18 18:28:10,245] {processor.py:163} INFO - Started process (PID=2520) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:28:10,247] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:28:10,248] {logging_mixin.py:109} INFO - [2021-10-18 18:28:10,247] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:28:10,343] {logging_mixin.py:109} INFO - [2021-10-18 18:28:10,341] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:28:10,357] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:28:10,364] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.122 seconds
[2021-10-18 18:28:40,450] {processor.py:163} INFO - Started process (PID=2552) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:28:40,452] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:28:40,453] {logging_mixin.py:109} INFO - [2021-10-18 18:28:40,453] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:28:40,564] {logging_mixin.py:109} INFO - [2021-10-18 18:28:40,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:28:40,576] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:28:40,582] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.135 seconds
[2021-10-18 18:29:10,648] {processor.py:163} INFO - Started process (PID=2573) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:29:10,650] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:29:10,651] {logging_mixin.py:109} INFO - [2021-10-18 18:29:10,651] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:29:10,758] {logging_mixin.py:109} INFO - [2021-10-18 18:29:10,757] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:29:10,772] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:29:10,777] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.134 seconds
[2021-10-18 18:29:40,858] {processor.py:163} INFO - Started process (PID=2606) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:29:40,860] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:29:40,861] {logging_mixin.py:109} INFO - [2021-10-18 18:29:40,861] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:29:40,958] {logging_mixin.py:109} INFO - [2021-10-18 18:29:40,956] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:29:40,972] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:29:40,978] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.124 seconds
[2021-10-18 18:30:11,055] {processor.py:163} INFO - Started process (PID=2627) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:30:11,057] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:30:11,058] {logging_mixin.py:109} INFO - [2021-10-18 18:30:11,058] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:30:11,158] {logging_mixin.py:109} INFO - [2021-10-18 18:30:11,156] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:30:11,173] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:30:11,179] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.129 seconds
[2021-10-18 18:30:41,256] {processor.py:163} INFO - Started process (PID=2658) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:30:41,258] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:30:41,259] {logging_mixin.py:109} INFO - [2021-10-18 18:30:41,259] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:30:41,366] {logging_mixin.py:109} INFO - [2021-10-18 18:30:41,365] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:30:41,379] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:30:41,385] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.134 seconds
[2021-10-18 18:31:11,455] {processor.py:163} INFO - Started process (PID=2679) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:31:11,457] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:31:11,459] {logging_mixin.py:109} INFO - [2021-10-18 18:31:11,459] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:31:11,562] {logging_mixin.py:109} INFO - [2021-10-18 18:31:11,560] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:31:11,575] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:31:11,582] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.131 seconds
[2021-10-18 18:31:41,658] {processor.py:163} INFO - Started process (PID=2711) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:31:41,660] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:31:41,662] {logging_mixin.py:109} INFO - [2021-10-18 18:31:41,662] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:31:41,780] {logging_mixin.py:109} INFO - [2021-10-18 18:31:41,778] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:31:41,796] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:31:41,804] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.150 seconds
[2021-10-18 18:32:11,885] {processor.py:163} INFO - Started process (PID=2732) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:32:11,887] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:32:11,888] {logging_mixin.py:109} INFO - [2021-10-18 18:32:11,888] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:32:11,993] {logging_mixin.py:109} INFO - [2021-10-18 18:32:11,992] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:32:12,008] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:32:12,014] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.133 seconds
[2021-10-18 18:32:42,073] {processor.py:163} INFO - Started process (PID=2764) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:32:42,075] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:32:42,076] {logging_mixin.py:109} INFO - [2021-10-18 18:32:42,076] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:32:42,188] {logging_mixin.py:109} INFO - [2021-10-18 18:32:42,186] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:32:42,211] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:32:42,220] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.151 seconds
[2021-10-18 18:33:12,286] {processor.py:163} INFO - Started process (PID=2786) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:33:12,288] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:33:12,289] {logging_mixin.py:109} INFO - [2021-10-18 18:33:12,289] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:33:12,388] {logging_mixin.py:109} INFO - [2021-10-18 18:33:12,386] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:33:12,403] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:33:12,409] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.126 seconds
[2021-10-18 18:33:42,489] {processor.py:163} INFO - Started process (PID=2817) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:33:42,491] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:33:42,492] {logging_mixin.py:109} INFO - [2021-10-18 18:33:42,492] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:33:42,603] {logging_mixin.py:109} INFO - [2021-10-18 18:33:42,602] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:33:42,617] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:33:42,623] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.139 seconds
[2021-10-18 18:34:12,685] {processor.py:163} INFO - Started process (PID=2838) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:34:12,688] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:34:12,689] {logging_mixin.py:109} INFO - [2021-10-18 18:34:12,689] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:34:12,799] {logging_mixin.py:109} INFO - [2021-10-18 18:34:12,797] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:34:12,813] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:34:12,818] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.138 seconds
[2021-10-18 18:34:42,883] {processor.py:163} INFO - Started process (PID=2870) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:34:42,885] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:34:42,887] {logging_mixin.py:109} INFO - [2021-10-18 18:34:42,886] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:34:42,991] {logging_mixin.py:109} INFO - [2021-10-18 18:34:42,989] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:34:43,006] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:34:43,013] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.134 seconds
[2021-10-18 18:35:13,075] {processor.py:163} INFO - Started process (PID=2891) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:35:13,078] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:35:13,079] {logging_mixin.py:109} INFO - [2021-10-18 18:35:13,079] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:35:13,176] {logging_mixin.py:109} INFO - [2021-10-18 18:35:13,174] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:35:13,190] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:35:13,196] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.125 seconds
[2021-10-18 18:35:43,290] {processor.py:163} INFO - Started process (PID=2923) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:35:43,293] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:35:43,294] {logging_mixin.py:109} INFO - [2021-10-18 18:35:43,294] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:35:43,422] {logging_mixin.py:109} INFO - [2021-10-18 18:35:43,421] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:35:43,437] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:35:43,442] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.156 seconds
[2021-10-18 18:36:13,504] {processor.py:163} INFO - Started process (PID=2944) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:36:13,506] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:36:13,507] {logging_mixin.py:109} INFO - [2021-10-18 18:36:13,507] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:36:13,606] {logging_mixin.py:109} INFO - [2021-10-18 18:36:13,605] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:36:13,619] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:36:13,625] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.125 seconds
[2021-10-18 18:36:43,705] {processor.py:163} INFO - Started process (PID=2976) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:36:43,707] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:36:43,708] {logging_mixin.py:109} INFO - [2021-10-18 18:36:43,708] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:36:43,812] {logging_mixin.py:109} INFO - [2021-10-18 18:36:43,810] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:36:43,826] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:36:43,832] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.132 seconds
[2021-10-18 18:37:13,904] {processor.py:163} INFO - Started process (PID=2997) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:37:13,907] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:37:13,908] {logging_mixin.py:109} INFO - [2021-10-18 18:37:13,908] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:37:14,018] {logging_mixin.py:109} INFO - [2021-10-18 18:37:14,017] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:37:14,034] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:37:14,041] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.141 seconds
[2021-10-18 18:37:44,116] {processor.py:163} INFO - Started process (PID=3030) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:37:44,120] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:37:44,121] {logging_mixin.py:109} INFO - [2021-10-18 18:37:44,121] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:37:44,225] {logging_mixin.py:109} INFO - [2021-10-18 18:37:44,222] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:37:44,238] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:37:44,244] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.132 seconds
[2021-10-18 18:38:14,328] {processor.py:163} INFO - Started process (PID=3061) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:38:14,335] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:38:14,338] {logging_mixin.py:109} INFO - [2021-10-18 18:38:14,338] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:38:14,459] {logging_mixin.py:109} INFO - [2021-10-18 18:38:14,458] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:38:14,475] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:38:14,482] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.165 seconds
[2021-10-18 18:38:44,550] {processor.py:163} INFO - Started process (PID=3083) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:38:44,551] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:38:44,553] {logging_mixin.py:109} INFO - [2021-10-18 18:38:44,553] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:38:44,655] {logging_mixin.py:109} INFO - [2021-10-18 18:38:44,653] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:38:44,668] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:38:44,674] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.128 seconds
[2021-10-18 18:39:14,741] {processor.py:163} INFO - Started process (PID=3114) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:39:14,743] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:39:14,744] {logging_mixin.py:109} INFO - [2021-10-18 18:39:14,744] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:39:14,849] {logging_mixin.py:109} INFO - [2021-10-18 18:39:14,848] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:39:14,863] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:39:14,868] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.131 seconds
[2021-10-18 18:39:44,944] {processor.py:163} INFO - Started process (PID=3135) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:39:44,946] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:39:44,948] {logging_mixin.py:109} INFO - [2021-10-18 18:39:44,948] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:39:45,073] {logging_mixin.py:109} INFO - [2021-10-18 18:39:45,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 20, in <module>
    connection_credentials = {username:'neo4j',password:'Reddit123!',database:'system'}
NameError: name 'username' is not defined
[2021-10-18 18:39:45,090] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:39:45,096] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.157 seconds
[2021-10-18 18:40:09,142] {processor.py:163} INFO - Started process (PID=3156) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:40:09,143] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:40:09,144] {logging_mixin.py:109} INFO - [2021-10-18 18:40:09,144] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:40:09,151] {logging_mixin.py:109} INFO - [2021-10-18 18:40:09,150] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 44
    t1 PythonOperator(
                    ^
SyntaxError: invalid syntax
[2021-10-18 18:40:09,167] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:40:09,173] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.035 seconds
[2021-10-18 18:40:39,262] {processor.py:163} INFO - Started process (PID=3187) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:40:39,264] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:40:39,265] {logging_mixin.py:109} INFO - [2021-10-18 18:40:39,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:40:39,271] {logging_mixin.py:109} INFO - [2021-10-18 18:40:39,270] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 44
    t1 PythonOperator(
                    ^
SyntaxError: invalid syntax
[2021-10-18 18:40:39,286] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:40:39,296] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.036 seconds
[2021-10-18 18:41:09,362] {processor.py:163} INFO - Started process (PID=3208) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:41:09,363] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:41:09,364] {logging_mixin.py:109} INFO - [2021-10-18 18:41:09,364] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:09,370] {logging_mixin.py:109} INFO - [2021-10-18 18:41:09,369] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 44
    t1 PythonOperator(
                    ^
SyntaxError: invalid syntax
[2021-10-18 18:41:09,389] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:09,396] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.037 seconds
[2021-10-18 18:41:10,371] {processor.py:163} INFO - Started process (PID=3209) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:41:10,373] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:41:10,374] {logging_mixin.py:109} INFO - [2021-10-18 18:41:10,374] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:10,489] {logging_mixin.py:109} INFO - [2021-10-18 18:41:10,487] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:41:10,503] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:10,508] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.142 seconds
[2021-10-18 18:41:40,547] {processor.py:163} INFO - Started process (PID=3240) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:41:40,549] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:41:40,550] {logging_mixin.py:109} INFO - [2021-10-18 18:41:40,550] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:40,653] {logging_mixin.py:109} INFO - [2021-10-18 18:41:40,652] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:41:40,667] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:40,673] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.130 seconds
[2021-10-18 18:41:44,583] {processor.py:163} INFO - Started process (PID=3241) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:41:44,584] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:41:44,585] {logging_mixin.py:109} INFO - [2021-10-18 18:41:44,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:44,704] {logging_mixin.py:109} INFO - [2021-10-18 18:41:44,703] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:41:44,718] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:41:44,723] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.144 seconds
[2021-10-18 18:42:14,799] {processor.py:163} INFO - Started process (PID=3274) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:42:14,801] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:42:14,812] {logging_mixin.py:109} INFO - [2021-10-18 18:42:14,812] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:42:14,926] {logging_mixin.py:109} INFO - [2021-10-18 18:42:14,925] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:42:14,942] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:42:14,950] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.155 seconds
[2021-10-18 18:42:45,022] {processor.py:163} INFO - Started process (PID=3298) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:42:45,024] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:42:45,025] {logging_mixin.py:109} INFO - [2021-10-18 18:42:45,025] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:42:45,141] {logging_mixin.py:109} INFO - [2021-10-18 18:42:45,139] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:42:45,154] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:42:45,161] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.142 seconds
[2021-10-18 18:43:15,211] {processor.py:163} INFO - Started process (PID=3329) to work on /opt/airflow/dags/olympics.py
[2021-10-18 18:43:15,213] {processor.py:620} INFO - Processing file /opt/airflow/dags/olympics.py for tasks to queue
[2021-10-18 18:43:15,214] {logging_mixin.py:109} INFO - [2021-10-18 18:43:15,214] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/olympics.py
[2021-10-18 18:43:15,315] {logging_mixin.py:109} INFO - [2021-10-18 18:43:15,313] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/olympics.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/olympics.py", line 8, in <module>
    from create_databases import create_database
ModuleNotFoundError: No module named 'create_databases'
[2021-10-18 18:43:15,329] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/olympics.py
[2021-10-18 18:43:15,335] {processor.py:171} INFO - Processing /opt/airflow/dags/olympics.py took 0.127 seconds
